/*
 * Courier service
 * Service for package delivery
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.courier;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import org.bp.courier.Person;

/**
 * CourierRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-28T16:06:56.714+01:00[Europe/Belgrade]")
public class CourierRequest {
  @SerializedName("courierType")
  private String courierType = null;

  @SerializedName("person")
  private org.bp.courier.Person person = null;

  public CourierRequest courierType(String courierType) {
    this.courierType = courierType;
    return this;
  }

   /**
   * Get courierType
   * @return courierType
  **/
  
  public String getCourierType() {
    return courierType;
  }

  public void setCourierType(String courierType) {
    this.courierType = courierType;
  }

  public CourierRequest person(org.bp.courier.Person person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  
  public org.bp.courier.Person getPerson() {
    return person;
  }

  public void setPerson(Person person) {
    this.person = person;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CourierRequest courierRequest = (CourierRequest) o;
    return Objects.equals(this.courierType, courierRequest.courierType) &&
        Objects.equals(this.person, courierRequest.person);
  }

  @Override
  public int hashCode() {
    return Objects.hash(courierType, person);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CourierRequest {\n");
    
    sb.append("    courierType: ").append(toIndentedString(courierType)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
