INSERT INTO MYST_MAJOR_CITIES VALUES ('PL', 'Szczyrk', TREAT(ST_POINT.FROM_WKT('POINT(19.036107 49.718655)') AS ST_POINT));

desc MYST_MAJOR_CITIES;

desc RIVERS;

SELECT name, (ST_GEOMETRY(GEOM)).GET_WKT() WKT FROM RIVERS;

SELECT SDO_UTIL.TO_GMLGEOMETRY(ST_POINT.GET_SDO_GEOM(stgeom)) FROM MYST_MAJOR_CITIES where CITY_NAME='Szczyrk';