/*
 * Payment service
 * Service for payment
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.payment;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import org.bp.payment.Amount;
import org.bp.payment.PaymentBlik;
import org.bp.payment.PaymentCard;

/**
 * PaymentRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-28T16:06:58.840+01:00[Europe/Belgrade]")
public class PaymentRequest {
  @SerializedName("paymentBlik")
  private org.bp.payment.PaymentBlik paymentBlik = null;

  @SerializedName("paymentCard")
  private org.bp.payment.PaymentCard paymentCard = null;

  @SerializedName("amount")
  private org.bp.payment.Amount amount = null;

  public PaymentRequest paymentBlik(org.bp.payment.PaymentBlik paymentBlik) {
    this.paymentBlik = paymentBlik;
    return this;
  }

   /**
   * Get paymentBlik
   * @return paymentBlik
  **/
  
  public org.bp.payment.PaymentBlik getPaymentBlik() {
    return paymentBlik;
  }

  public void setPaymentBlik(PaymentBlik paymentBlik) {
    this.paymentBlik = paymentBlik;
  }

  public PaymentRequest paymentCard(org.bp.payment.PaymentCard paymentCard) {
    this.paymentCard = paymentCard;
    return this;
  }

   /**
   * Get paymentCard
   * @return paymentCard
  **/
  
  public org.bp.payment.PaymentCard getPaymentCard() {
    return paymentCard;
  }

  public void setPaymentCard(PaymentCard paymentCard) {
    this.paymentCard = paymentCard;
  }

  public PaymentRequest amount(org.bp.payment.Amount amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  
  public org.bp.payment.Amount getAmount() {
    return amount;
  }

  public void setAmount(Amount amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentRequest paymentRequest = (PaymentRequest) o;
    return Objects.equals(this.paymentBlik, paymentRequest.paymentBlik) &&
        Objects.equals(this.paymentCard, paymentRequest.paymentCard) &&
        Objects.equals(this.amount, paymentRequest.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentBlik, paymentCard, amount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentRequest {\n");
    
    sb.append("    paymentBlik: ").append(toIndentedString(paymentBlik)).append("\n");
    sb.append("    paymentCard: ").append(toIndentedString(paymentCard)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
